import { Money } from './money.js';
import type { Currency } from './money.js';

/*
 * Re-exported because `unpackAttestation` RETURNS a Money, and this module is
 * consumed through the `@emil/domain/attestation` subpath by `apps/web` — which
 * has no other route to the class. A caller that can read an attestation but
 * cannot render the amount inside it has been handed half a tool.
 */
export { Money };
export type { Currency };

/**
 * A document that proves itself, to a phone with no signal and a shop with no
 * server.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS EXISTS: THE QR USED TO BE A POINTER.
 *
 * The verification QR encoded `…/verify#d=<digest>` — a REFERENCE. Scanning it
 * sent the reader's phone to ask this system whether that digest was real. That
 * works exactly as long as this system is running and reachable, which for a
 * shop whose books live on one PC means: during shop hours, on that WiFi, until
 * the PC is replaced. A warranty card outlives all three. The customer standing
 * there in 2031 gets a dead link, and no amount of hosting fixes a URL that was
 * printed in 2026.
 *
 * So the QR stops pointing and starts CARRYING. The figures a reader wants to
 * check — what kind of document, its number, its date, its total — travel
 * inside the code, signed. The reader's own browser checks the signature
 * against a public key and compares the figures to the paper in their hand. No
 * server is asked. Nothing has to still be running.
 *
 * WHAT THIS PROVES, EXACTLY: that whoever holds the private key issued a
 * document with these figures. It is a point-in-time attestation, and it CANNOT
 * say the document was not later cancelled or credited — for that the reader
 * needs the live system, which is why `/verify` still asks when it can. Offline
 * gives certainty about the paper; online adds current status. Neither replaces
 * the other and the UI says which it used.
 *
 * ---------------------------------------------------------------------------
 * WHY BINARY, WHICH LOOKS LIKE PREMATURE CLEVERNESS AND IS NOT.
 *
 * `encodeQr` in `qr.ts` stops at version 10, EC level M — 213 usable bytes. The
 * obvious implementation, JSON plus a signature, measures 233 bytes and throws
 * at the printer. Not in a test, not in review: at the counter, on the first
 * receipt with a long document number, after everything looked fine.
 *
 * A 64-byte ECDSA signature is the floor and cannot be shrunk without giving up
 * security, so the saving has to come from the payload. Packed as fixed-width
 * fields it is 14 bytes plus the document number — around 27 in practice, 36
 * once base64url'd — and the whole URL lands near 160 bytes, comfortably inside
 * version 9. `attestation.test.ts` asserts the fit rather than trusting this
 * paragraph.
 * ---------------------------------------------------------------------------
 */

/** Documents that can carry a signed attestation. Order is part of the format. */
export const ATTESTED_TYPES = ['INVOICE', 'RECEIPT', 'REPAIR_JOB', 'WARRANTY'] as const;

export type AttestedType = (typeof ATTESTED_TYPES)[number];

/**
 * Format version, in the high nibble of byte 0.
 *
 * A reader that meets a version it does not know must say so plainly rather
 * than guess at the layout — a verifier that misreads an amount and still
 * reports GENUINE is worse than one that admits it cannot tell.
 */
export const ATTESTATION_VERSION = 1;

/**
 * Day zero for the packed date.
 *
 * 2000-01-01 with a 16-bit day count reaches 2179-06-06 exactly — stated to the
 * day rather than to the year, because a range written as "to 2179" is a range
 * somebody will test at 2179-12-31 and find is a lie. It outlives every
 * retention period this system will be asked about, and still admits
 * back-dated documents from before the shop opened.
 */
const EPOCH_DAYS_UTC = Date.UTC(2000, 0, 1) / 86_400_000;
const MAX_DAYS = 0xffff;
/** The last packable day, as text, so the error can name it. */
export const MAX_ATTESTABLE_DATE = '2179-06-06';

/** Six bytes of minor units at MONEY_SCALE: to about RM 28 billion per document. */
const MAX_UNITS = 0xffff_ffff_ffffn;

const PREFIX_BYTES = 14;
const MAX_DOCUMENT_NO = 64;

/**
 * The document number charset.
 *
 * Deliberately narrow — this is generated by `numbering.ts`, never typed by a
 * user, and a narrow set means one byte per character with no encoding
 * question. A number outside it is a bug upstream, so it throws rather than
 * being mangled into something that would verify against the wrong document.
 */
const DOCUMENT_NO_PATTERN = /^[A-Za-z0-9/-]+$/;

export interface DocumentAttestation {
  readonly documentType: AttestedType;
  /** Accounting date — `YYYY-MM-DD`, never a timestamp. */
  readonly issuedOn: string;
  readonly total: Money;
  /** Four bytes identifying the issuing tenant, as hex. See `tenantTag()`. */
  readonly tenantTag: string;
  readonly documentNo: string;
}

/**
 * Four bytes of the tenant's UUID, so figures from one shop cannot be replayed
 * as another's.
 *
 * Not a secret and not a hash — a UUID is already opaque, and four bytes of one
 * identifies the tenant to a verifier that has the list without revealing it to
 * one that does not. It exists to bind the attestation to an issuer, not to
 * hide anything.
 */
export function tenantTag(tenantId: string): string {
  const hex = tenantId.replace(/-/g, '');
  if (!/^[0-9a-fA-F]{32}$/.test(hex)) {
    throw new TypeError(`Not a UUID: ${tenantId}`);
  }
  return hex.slice(0, 8).toLowerCase();
}

function daysSinceEpoch(isoDate: string): number {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(isoDate);
  if (!match) throw new TypeError(`Not an ISO date (YYYY-MM-DD): ${isoDate}`);

  const [, y, m, d] = match;
  const utc = Date.UTC(Number(y), Number(m) - 1, Number(d));
  // Date.UTC happily rolls 2026-02-31 into March; compare back so it cannot.
  const days = utc / 86_400_000 - EPOCH_DAYS_UTC;
  if (!Number.isInteger(days) || days < 0 || days > MAX_DAYS) {
    throw new RangeError(
      `Date outside the attestable range (2000-01-01 to ${MAX_ATTESTABLE_DATE}): ${isoDate}`,
    );
  }
  if (new Date(utc).toISOString().slice(0, 10) !== isoDate) {
    throw new RangeError(`Not a real calendar date: ${isoDate}`);
  }
  return days;
}

function isoFromDays(days: number): string {
  return new Date((days + EPOCH_DAYS_UTC) * 86_400_000).toISOString().slice(0, 10);
}

/**
 * Pack an attestation into its wire form.
 *
 *   byte  0      version (high nibble) | document type (low nibble)
 *   bytes 1..2   issue date, days since 2000-01-01, big-endian
 *   bytes 3..8   total in minor units at MONEY_SCALE, big-endian
 *   bytes 9..12  tenant tag
 *   byte  13     document number length
 *   bytes 14..   document number, one byte per character
 */
export function packAttestation(attestation: DocumentAttestation): Uint8Array<ArrayBuffer> {
  const { documentType, issuedOn, total, tenantTag: tag, documentNo } = attestation;

  const typeIndex = ATTESTED_TYPES.indexOf(documentType);
  if (typeIndex === -1) throw new TypeError(`Not an attestable type: ${documentType}`);

  if (total.units < 0n) {
    // A negative total would need a sign bit and no attested document has one:
    // a credit note is its own document with its own positive total.
    throw new RangeError(`Cannot attest a negative total: ${total.toString()}`);
  }
  if (total.units > MAX_UNITS) {
    throw new RangeError(`Total too large to attest: ${total.toString()}`);
  }
  if (!/^[0-9a-f]{8}$/.test(tag)) throw new TypeError(`Not a tenant tag: ${tag}`);
  if (!DOCUMENT_NO_PATTERN.test(documentNo) || documentNo.length > MAX_DOCUMENT_NO) {
    throw new TypeError(`Not a packable document number: ${documentNo}`);
  }

  const out = new Uint8Array(PREFIX_BYTES + documentNo.length);
  out[0] = (ATTESTATION_VERSION << 4) | typeIndex;

  const days = daysSinceEpoch(issuedOn);
  out[1] = (days >> 8) & 0xff;
  out[2] = days & 0xff;

  let units = total.units;
  for (let i = 8; i >= 3; i -= 1) {
    out[i] = Number(units & 0xffn);
    units >>= 8n;
  }

  for (let i = 0; i < 4; i += 1) {
    out[9 + i] = Number.parseInt(tag.slice(i * 2, i * 2 + 2), 16);
  }

  out[13] = documentNo.length;
  for (let i = 0; i < documentNo.length; i += 1) {
    out[PREFIX_BYTES + i] = documentNo.charCodeAt(i);
  }
  return out;
}

/**
 * Read an attestation back, or throw.
 *
 * Every failure here is a refusal, never a best guess — this runs in front of a
 * person deciding whether a piece of paper is real, and "probably" is not an
 * answer that helps them.
 */
export function unpackAttestation(
  bytes: Uint8Array<ArrayBufferLike>,
  currency: Currency,
): DocumentAttestation {
  if (bytes.length < PREFIX_BYTES) {
    throw new RangeError(`Attestation truncated: ${bytes.length} bytes`);
  }

  const version = bytes[0]! >> 4;
  if (version !== ATTESTATION_VERSION) {
    throw new RangeError(
      `Attestation format v${version} is newer than this reader (v${ATTESTATION_VERSION})`,
    );
  }

  const documentType = ATTESTED_TYPES[bytes[0]! & 0x0f];
  if (!documentType) throw new RangeError(`Unknown document type in attestation`);

  const length = bytes[13]!;
  if (bytes.length !== PREFIX_BYTES + length) {
    throw new RangeError(
      `Attestation length mismatch: header says ${length}, got ${bytes.length - PREFIX_BYTES}`,
    );
  }

  let units = 0n;
  for (let i = 3; i <= 8; i += 1) units = (units << 8n) | BigInt(bytes[i]!);

  let documentNo = '';
  for (let i = 0; i < length; i += 1) documentNo += String.fromCharCode(bytes[PREFIX_BYTES + i]!);
  if (!DOCUMENT_NO_PATTERN.test(documentNo)) {
    throw new RangeError('Attestation carries a document number outside the charset');
  }

  let tag = '';
  for (let i = 9; i <= 12; i += 1) tag += bytes[i]!.toString(16).padStart(2, '0');

  return {
    documentType,
    issuedOn: isoFromDays((bytes[1]! << 8) | bytes[2]!),
    total: Money.fromUnits(units, currency),
    tenantTag: tag,
    documentNo,
  };
}

// ---------------------------------------------------------------------------
// base64url
//
// Hand-rolled rather than `Buffer` (Node-only) or `btoa` (whose Latin-1 detour
// is a trap for byte data), because this module is imported by the API, by the
// browser, and by tests, and must mean exactly one thing in all three.
// ---------------------------------------------------------------------------

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';

export function toBase64Url(bytes: Uint8Array<ArrayBufferLike>): string {
  let out = '';
  for (let i = 0; i < bytes.length; i += 3) {
    const a = bytes[i]!;
    const b = bytes[i + 1];
    const c = bytes[i + 2];
    out += ALPHABET[a >> 2]!;
    out += ALPHABET[((a & 0x03) << 4) | ((b ?? 0) >> 4)]!;
    if (b === undefined) break;
    out += ALPHABET[((b & 0x0f) << 2) | ((c ?? 0) >> 6)]!;
    if (c === undefined) break;
    out += ALPHABET[c & 0x3f]!;
  }
  return out;
}

/*
 * DECODING IS A REFUSAL OR AN ANSWER, NEVER A BEST GUESS.
 *
 * This ran in front of someone deciding whether a piece of paper is real, and
 * it accepted two kinds of string it should not have.
 *
 * IMPOSSIBLE LENGTHS. Every group of four characters carries three bytes, so a
 * remainder of two characters means one byte and three means two. A remainder
 * of ONE encodes six bits and no whole byte — no encoder can produce it. The
 * old loop simply dropped the orphan and returned the rest, so `"A"` decoded
 * to zero bytes and `"AAAAA"` to three.
 *
 * LEFTOVER BITS NOBODY WROTE. The trailing characters of a short group carry
 * padding bits that the encoder always leaves zero, and the loop ignored them.
 * Measured on a real attestation payload: of the 63 possible single-character
 * typos in the LAST position, three decoded to a byte-identical attestation —
 * `…DAwNDI`, `…DAwNDJ`, `…DAwNDK` and `…DAwNDL` all read back as PAY-00042 for
 * RM 1,234.50. A mistyped code that verifies is worse than one that fails,
 * because the failure is the part that tells somebody to look again.
 *
 * Neither was a forgery path — the signature is computed over the DECODED
 * bytes, so a collision here gains an attacker nothing. Both are refusals this
 * module claims to make and did not.
 */
export function fromBase64Url(text: string): Uint8Array<ArrayBuffer> {
  const clean = text.trim();
  if (clean === '') return new Uint8Array(0);
  if (!/^[A-Za-z0-9_-]+$/.test(clean)) {
    throw new TypeError('Not base64url');
  }
  if (clean.length % 4 === 1) {
    throw new TypeError('Not base64url: a trailing character encodes no whole byte');
  }

  const bytes: number[] = [];
  let buffer = 0;
  let bits = 0;
  for (const char of clean) {
    buffer = (buffer << 6) | ALPHABET.indexOf(char);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes.push((buffer >> bits) & 0xff);
    }
  }

  // 0, 2 or 4 bits are left over, and an encoder writes them as zero. Anything
  // else is a string this decoder did not produce.
  if (bits > 0 && (buffer & ((1 << bits) - 1)) !== 0) {
    throw new TypeError('Not base64url: the final character sets bits that carry no data');
  }

  return Uint8Array.from(bytes);
}
